#!/usr/bin/env bash
# bash script that installs Nginx & makes configurations to meet the following requirements:
#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
server_hostname=$(hostname)

# Configure Nginx to add custom HTTP response header
custom_header="add_header X-Served-By $server_hostname;"
sudo sed -i "/server_name _;/a \ \ \ \ $custom_header" /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
