#!/usr/bin/env bash
# The script to install nginx on a web server.
#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Create a default Nginx configuration file at /etc/nginx/sites-available/default
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;

    location / {
        echo 'Holberton School for the win!';
    }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
